import type { Exercice, Famille, Materiel, Phase, ZoneCorps } from './types';

/* ----------------------------------------------------------------------
 * Le deck d'exercices.
 *
 * Tout se fait dans un salon, sans matériel obligatoire. Chaque exercice
 * porte son niveau sonore (vital en appartement) et un `niveauRequis` :
 * le deck s'agrandit au fil des niveaux, ce qui fait qu'une séance du
 * niveau 12 ne ressemble pas à une séance du niveau 2 même en tirant au
 * hasard. C'est le principal remède à la lassitude.
 * -------------------------------------------------------------------- */

export const CATALOGUE: Exercice[] = [
  /* ---------------------- Échauffement / mobilité ---------------------- */
  {
    id: 'cercles_bras',
    nom: 'Cercles de bras',
    emoji: '🔄',
    famille: 'mobilite',
    phases: ['echauffement'],
    stats: { souplesse: 0.4 },
    difficulte: 1,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Grands cercles avec les bras tendus, en avant puis en arrière.',
    astuce: 'Amplitude maximale, épaules relâchées.',
    zones: ['epaules', 'poitrine'],
    niveauRequis: 1,
  },
  {
    id: 'rotation_hanches',
    nom: 'Rotations de hanches',
    emoji: '🌀',
    famille: 'mobilite',
    phases: ['echauffement'],
    stats: { souplesse: 0.4 },
    difficulte: 1,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Mains sur les hanches, dessine des grands cercles avec le bassin.',
    zones: ['hanches', 'tronc'],
    niveauRequis: 1,
  },
  {
    id: 'chat_vache',
    nom: 'Chat / vache',
    emoji: '🐈',
    famille: 'mobilite',
    phases: ['echauffement', 'retour_calme'],
    stats: { souplesse: 0.6 },
    difficulte: 1,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'À quatre pattes, alterne dos rond et dos creux, lentement.',
    astuce: 'Synchronise : j\'expire en dos rond, j\'inspire en dos creux.',
    zones: ['dos', 'tronc'],
    niveauRequis: 1,
  },
  {
    id: 'balancier_jambes',
    nom: 'Balancier de jambe',
    emoji: '🦵',
    famille: 'mobilite',
    phases: ['echauffement'],
    stats: { souplesse: 0.5 },
    difficulte: 1,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Appuie-toi d\'une main et balance la jambe d\'avant en arrière. Change à mi-temps.',
    zones: ['hanches', 'jambes'],
    niveauRequis: 1,
  },
  {
    id: 'rotation_epaules',
    nom: 'Déverrouillage des épaules',
    emoji: '🙆',
    famille: 'mobilite',
    phases: ['echauffement'],
    stats: { souplesse: 0.5 },
    difficulte: 1,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Monte les épaules vers les oreilles, roule vers l\'arrière, relâche.',
    zones: ['epaules', 'nuque'],
    niveauRequis: 1,
  },
  {
    id: 'torsion_buste',
    nom: 'Torsions du buste',
    emoji: '🌪️',
    famille: 'mobilite',
    phases: ['echauffement'],
    stats: { souplesse: 0.5 },
    difficulte: 1,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Pieds ancrés, fais pivoter le buste de gauche à droite, bras relâchés.',
    zones: ['tronc', 'dos'],
    niveauRequis: 1,
  },
  {
    id: 'montees_genoux_douces',
    nom: 'Montées de genoux tranquilles',
    emoji: '🚶',
    famille: 'mobilite',
    phases: ['echauffement'],
    stats: { cardio: 0.4, souplesse: 0.2 },
    difficulte: 1,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Sur place, monte les genoux à hauteur de hanche, sans sauter.',
    zones: ['jambes', 'hanches'],
    niveauRequis: 1,
  },
  {
    id: 'fente_mobilite',
    nom: 'Fente + ouverture',
    emoji: '🧭',
    famille: 'mobilite',
    phases: ['echauffement'],
    stats: { souplesse: 0.7 },
    difficulte: 2,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'En fente avant, pose la main au sol et ouvre le buste vers le ciel. Alterne.',
    astuce: 'Le meilleur échauffement de hanches qui existe. Ne le saute pas.',
    zones: ['hanches', 'jambes'],
    niveauRequis: 2,
  },

  /* ------------------------------ Pousse ------------------------------ */
  {
    id: 'pompes_genoux',
    nom: 'Pompes sur les genoux',
    emoji: '🫸',
    famille: 'pousse',
    phases: ['bloc'],
    stats: { force: 0.8, gainage: 0.2 },
    difficulte: 1,
    mesure: 'reps',
    base: 10,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Genoux au sol, mains sous les épaules, descends la poitrine vers le sol.',
    astuce: 'Garde une ligne droite genoux-hanches-épaules : pas de fesses en l\'air.',
    niveauRequis: 1,
    plusDur: 'pompes',
  },
  {
    id: 'pompes_inclinees',
    nom: 'Pompes inclinées',
    emoji: '📐',
    famille: 'pousse',
    phases: ['bloc'],
    stats: { force: 0.8, gainage: 0.2 },
    difficulte: 2,
    mesure: 'reps',
    base: 10,
    materiel: ['chaise'],
    bruit: 'silencieux',
    consigne: 'Mains sur le bord d\'une chaise ou du canapé, corps gainé, descends la poitrine.',
    niveauRequis: 1,
    plusFacile: 'pompes_genoux',
    plusDur: 'pompes',
  },
  {
    id: 'pompes',
    nom: 'Pompes',
    emoji: '💥',
    famille: 'pousse',
    phases: ['bloc'],
    stats: { force: 1, gainage: 0.3 },
    difficulte: 3,
    mesure: 'reps',
    base: 10,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Mains un peu plus larges que les épaules, coudes à 45°, poitrine au sol.',
    astuce: 'Serre les fessiers : ça verrouille le bas du dos.',
    niveauRequis: 1,
    plusFacile: 'pompes_genoux',
    plusDur: 'pompes_diamant',
  },
  {
    id: 'pompes_diamant',
    nom: 'Pompes diamant',
    emoji: '💎',
    famille: 'pousse',
    phases: ['bloc'],
    stats: { force: 1, gainage: 0.3 },
    difficulte: 4,
    mesure: 'reps',
    base: 8,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Mains jointes sous la poitrine, pouces et index formant un losange.',
    astuce: 'Ça cible les triceps. Coudes qui frôlent le corps.',
    niveauRequis: 4,
    plusFacile: 'pompes',
  },
  {
    id: 'pompes_declinees',
    nom: 'Pompes déclinées',
    emoji: '📉',
    famille: 'pousse',
    phases: ['bloc'],
    stats: { force: 1, gainage: 0.4 },
    difficulte: 4,
    mesure: 'reps',
    base: 8,
    materiel: ['chaise'],
    bruit: 'silencieux',
    consigne: 'Pieds surélevés sur la chaise, mains au sol. Descends la poitrine.',
    niveauRequis: 5,
    plusFacile: 'pompes',
  },
  {
    id: 'pompes_pike',
    nom: 'Pompes en V',
    emoji: '⛰️',
    famille: 'pousse',
    phases: ['bloc'],
    stats: { force: 1, gainage: 0.3, souplesse: 0.2 },
    difficulte: 4,
    mesure: 'reps',
    base: 8,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Fesses hautes en V inversé, descends le sommet du crâne vers le sol.',
    astuce: 'La version maison du développé militaire : ça travaille les épaules.',
    niveauRequis: 6,
    plusFacile: 'pompes',
  },
  {
    id: 'pompes_archer',
    nom: 'Pompes archer',
    emoji: '🏹',
    famille: 'pousse',
    phases: ['bloc'],
    stats: { force: 1, gainage: 0.4 },
    difficulte: 5,
    mesure: 'reps',
    base: 6,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Mains très larges, descends d\'un seul côté en tendant le bras opposé. Alterne.',
    niveauRequis: 10,
    plusFacile: 'pompes',
  },
  {
    id: 'dips_chaise',
    nom: 'Dips sur chaise',
    emoji: '🪑',
    famille: 'pousse',
    phases: ['bloc'],
    stats: { force: 0.9 },
    difficulte: 3,
    mesure: 'reps',
    base: 10,
    materiel: ['chaise'],
    bruit: 'silencieux',
    consigne: 'Dos à la chaise, mains sur le bord, descends en pliant les coudes vers l\'arrière.',
    astuce: 'Ne descends pas plus bas que 90° à l\'épaule.',
    niveauRequis: 2,
  },
  {
    id: 'pompes_hindou',
    nom: 'Pompes hindoues',
    emoji: '🐍',
    famille: 'pousse',
    phases: ['bloc'],
    stats: { force: 0.7, souplesse: 0.5 },
    difficulte: 3,
    mesure: 'reps',
    base: 8,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Du V inversé, plonge la poitrine vers l\'avant en passant près du sol, puis remonte en cobra.',
    astuce: 'Un mouvement fluide, jamais saccadé.',
    niveauRequis: 5,
  },

  /* ------------------------------- Tire ------------------------------- */
  {
    id: 'superman',
    nom: 'Superman',
    emoji: '🦸',
    famille: 'tire',
    phases: ['bloc'],
    stats: { force: 0.5, gainage: 0.6 },
    difficulte: 1,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'À plat ventre, décolle bras et jambes du sol et tiens.',
    astuce: 'Regarde le sol : la nuque reste dans l\'axe.',
    niveauRequis: 1,
  },
  {
    id: 'rowing_serviette',
    nom: 'Tirage à la serviette',
    emoji: '🧻',
    famille: 'tire',
    phases: ['bloc'],
    stats: { force: 0.8 },
    difficulte: 2,
    mesure: 'reps',
    base: 12,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Tiens une serviette à deux mains et tire en écartant, en résistant avec le bras opposé.',
    astuce: 'C\'est toi qui crées la résistance : plus tu forces, plus c\'est dur.',
    niveauRequis: 1,
  },
  {
    id: 'y_t_w',
    nom: 'Y-T-W au sol',
    emoji: '🔤',
    famille: 'tire',
    phases: ['bloc'],
    stats: { force: 0.5, gainage: 0.4, souplesse: 0.3 },
    difficulte: 2,
    mesure: 'reps',
    base: 8,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'À plat ventre, décolle les bras en formant un Y, puis un T, puis un W. Ça fait 1 rep.',
    astuce: 'L\'antidote au dos voûté du bureau.',
    niveauRequis: 2,
  },
  {
    id: 'rowing_table',
    nom: 'Tirage australien sous la table',
    emoji: '🪵',
    famille: 'tire',
    phases: ['bloc'],
    stats: { force: 1, gainage: 0.3 },
    difficulte: 3,
    mesure: 'reps',
    base: 8,
    materiel: ['chaise'],
    bruit: 'silencieux',
    consigne: 'Allongé sous une table solide, attrape le bord et tire la poitrine vers le plateau.',
    astuce: 'Vérifie que la table tient ton poids avant de t\'y suspendre.',
    niveauRequis: 3,
  },
  {
    id: 'tirage_elastique',
    nom: 'Tirage à l\'élastique',
    emoji: '🎗️',
    famille: 'tire',
    phases: ['bloc'],
    stats: { force: 0.9 },
    difficulte: 2,
    mesure: 'reps',
    base: 12,
    materiel: ['elastique'],
    bruit: 'silencieux',
    consigne: 'Élastique ancré devant toi, tire les coudes vers l\'arrière en serrant les omoplates.',
    niveauRequis: 1,
  },
  {
    id: 'rowing_halteres',
    nom: 'Rowing haltères',
    emoji: '🏋️',
    famille: 'tire',
    phases: ['bloc'],
    stats: { force: 1 },
    difficulte: 2,
    mesure: 'reps',
    base: 12,
    materiel: ['halteres'],
    bruit: 'silencieux',
    consigne: 'Buste penché, dos plat, tire les haltères vers les hanches.',
    astuce: 'Pas de sac de courses : ça marche aussi avec deux bouteilles d\'eau.',
    niveauRequis: 1,
  },
  {
    id: 'pont_inverse',
    nom: 'Pont inversé',
    emoji: '🌉',
    famille: 'tire',
    phases: ['bloc'],
    stats: { force: 0.6, gainage: 0.5, souplesse: 0.3 },
    difficulte: 3,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Assis, mains derrière toi, pousse le bassin vers le haut jusqu\'à faire une table.',
    niveauRequis: 4,
  },

  /* ------------------------------ Jambes ------------------------------ */
  {
    id: 'squats',
    nom: 'Squats',
    emoji: '🦿',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.8, cardio: 0.2 },
    difficulte: 1,
    mesure: 'reps',
    base: 15,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Pieds largeur d\'épaules, descends comme pour t\'asseoir, poitrine haute.',
    astuce: 'Le poids dans les talons, les genoux suivent la pointe des pieds.',
    niveauRequis: 1,
    plusDur: 'squat_saute',
  },
  {
    id: 'squat_sumo',
    nom: 'Squat sumo',
    emoji: '🤼',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.8, souplesse: 0.3 },
    difficulte: 2,
    mesure: 'reps',
    base: 12,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Pieds très larges, pointes vers l\'extérieur, descends bien bas.',
    niveauRequis: 2,
  },
  {
    id: 'pont_fessier',
    nom: 'Pont fessier',
    emoji: '🌈',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.6, gainage: 0.4 },
    difficulte: 1,
    mesure: 'reps',
    base: 15,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Allongé sur le dos, pieds au sol, pousse le bassin vers le plafond.',
    astuce: 'Marque une seconde en haut en serrant les fessiers.',
    niveauRequis: 1,
    plusDur: 'pont_une_jambe',
  },
  {
    id: 'pont_une_jambe',
    nom: 'Pont fessier une jambe',
    emoji: '☝️',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.9, gainage: 0.4 },
    difficulte: 3,
    mesure: 'reps',
    base: 10,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Comme le pont fessier, mais une jambe tendue en l\'air. Alterne à mi-série.',
    niveauRequis: 4,
    plusFacile: 'pont_fessier',
  },
  {
    id: 'fentes',
    nom: 'Fentes alternées',
    emoji: '🚶‍♂️',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.8, cardio: 0.3 },
    difficulte: 2,
    mesure: 'reps',
    base: 12,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Grand pas en avant, genou arrière vers le sol, reviens. Alterne.',
    astuce: 'Le genou avant ne dépasse pas la pointe du pied.',
    niveauRequis: 1,
    plusDur: 'fentes_bulgares',
  },
  {
    id: 'fentes_bulgares',
    nom: 'Fentes bulgares',
    emoji: '🇧🇬',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 1, gainage: 0.3 },
    difficulte: 4,
    mesure: 'reps',
    base: 8,
    materiel: ['chaise'],
    bruit: 'silencieux',
    consigne: 'Pied arrière posé sur la chaise, descends sur la jambe avant. Alterne à mi-série.',
    astuce: 'L\'exercice le plus rentable pour les jambes à la maison. Et le plus détesté.',
    niveauRequis: 5,
    plusFacile: 'fentes',
  },
  {
    id: 'chaise_murale',
    nom: 'Chaise contre le mur',
    emoji: '🧱',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.7, gainage: 0.4 },
    difficulte: 2,
    mesure: 'temps',
    base: 45,
    materiel: ['mur'],
    bruit: 'silencieux',
    consigne: 'Dos plaqué au mur, cuisses à l\'horizontale. Tiens la position.',
    astuce: 'Si ça tremble, c\'est normal. Si ça brûle, c\'est que ça marche.',
    niveauRequis: 1,
  },
  {
    id: 'mollets',
    nom: 'Extensions mollets',
    emoji: '🦶',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.5 },
    difficulte: 1,
    mesure: 'reps',
    base: 20,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Monte lentement sur la pointe des pieds, redescends encore plus lentement.',
    niveauRequis: 1,
  },
  {
    id: 'montee_chaise',
    nom: 'Montées sur chaise',
    emoji: '🪜',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.8, cardio: 0.5 },
    difficulte: 3,
    mesure: 'reps',
    base: 12,
    materiel: ['chaise'],
    bruit: 'normal',
    consigne: 'Monte un pied sur la chaise, pousse pour te lever complètement, redescends en contrôle.',
    niveauRequis: 3,
  },
  {
    id: 'squat_saute',
    nom: 'Squats sautés',
    emoji: '🚀',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.7, cardio: 0.8 },
    difficulte: 4,
    mesure: 'reps',
    base: 10,
    materiel: [],
    bruit: 'bruyant',
    consigne: 'Descends en squat, explose vers le haut, amortis en douceur.',
    astuce: 'Réception silencieuse : genoux souples, pointe de pied d\'abord.',
    niveauRequis: 4,
    plusFacile: 'squats',
  },
  {
    id: 'fentes_sautees',
    nom: 'Fentes sautées',
    emoji: '✈️',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 0.7, cardio: 0.8 },
    difficulte: 4,
    mesure: 'reps',
    base: 10,
    materiel: [],
    bruit: 'bruyant',
    consigne: 'En fente, saute et change de jambe en l\'air.',
    niveauRequis: 6,
    plusFacile: 'fentes',
  },
  {
    id: 'pistol_assiste',
    nom: 'Squat pistolet assisté',
    emoji: '🎯',
    famille: 'jambes',
    phases: ['bloc'],
    stats: { force: 1, gainage: 0.4, souplesse: 0.3 },
    difficulte: 5,
    mesure: 'reps',
    base: 6,
    materiel: ['chaise'],
    bruit: 'silencieux',
    consigne: 'Sur une jambe, descends jusqu\'à effleurer la chaise, remonte. Alterne.',
    niveauRequis: 9,
    plusFacile: 'squats',
  },

  /* ------------------------------ Gainage ----------------------------- */
  {
    id: 'planche',
    nom: 'Planche',
    emoji: '🪚',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 1 },
    difficulte: 2,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Sur les avant-bras, corps parfaitement aligné. Ne laisse pas les hanches tomber.',
    astuce: 'Rentre le nombril, serre les fessiers. Respire.',
    niveauRequis: 1,
    plusDur: 'planche_tap',
  },
  {
    id: 'planche_laterale',
    nom: 'Planche latérale',
    emoji: '📏',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 1 },
    difficulte: 3,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Sur un avant-bras, corps de profil et bassin haut. Change de côté à mi-temps.',
    niveauRequis: 2,
  },
  {
    id: 'planche_tap',
    nom: 'Planche + touche d\'épaule',
    emoji: '👋',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 1, force: 0.3 },
    difficulte: 3,
    mesure: 'reps',
    base: 16,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'En planche bras tendus, touche l\'épaule opposée sans bouger le bassin.',
    astuce: 'Écarte les pieds pour plus de stabilité.',
    niveauRequis: 3,
    plusFacile: 'planche',
  },
  {
    id: 'dead_bug',
    nom: 'Dead bug',
    emoji: '🪲',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 0.9 },
    difficulte: 1,
    mesure: 'reps',
    base: 12,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Sur le dos, bras et genoux en l\'air. Tends bras et jambe opposés sans creuser le dos.',
    astuce: 'Le bas du dos reste collé au sol. C\'est toute la difficulté.',
    niveauRequis: 1,
  },
  {
    id: 'hollow_hold',
    nom: 'Hollow hold',
    emoji: '🌙',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 1 },
    difficulte: 3,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Sur le dos, bras et jambes décollés, lombaires plaquées au sol. Tiens la banane.',
    niveauRequis: 4,
  },
  {
    id: 'releves_jambes',
    nom: 'Relevés de jambes',
    emoji: '⬆️',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 0.9 },
    difficulte: 2,
    mesure: 'reps',
    base: 12,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Allongé, jambes tendues, monte-les à la verticale puis redescends sans toucher le sol.',
    niveauRequis: 2,
  },
  {
    id: 'crunch_velo',
    nom: 'Crunch vélo',
    emoji: '🚲',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 0.9, cardio: 0.2 },
    difficulte: 2,
    mesure: 'reps',
    base: 20,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Coude vers le genou opposé, en pédalant. Lentement, en contrôle.',
    astuce: 'Ne tire pas sur la nuque avec les mains.',
    niveauRequis: 1,
  },
  {
    id: 'mountain_climbers',
    nom: 'Mountain climbers',
    emoji: '🧗',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 0.7, cardio: 0.7 },
    difficulte: 3,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'normal',
    consigne: 'En planche bras tendus, ramène les genoux vers la poitrine en alternance, vite.',
    niveauRequis: 2,
  },
  {
    id: 'planche_dynamique',
    nom: 'Planche montée-descente',
    emoji: '🔃',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 0.9, force: 0.4 },
    difficulte: 3,
    mesure: 'reps',
    base: 12,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Passe de la planche sur les avant-bras à la planche bras tendus, et retour.',
    niveauRequis: 3,
  },
  {
    id: 'essuie_glace',
    nom: 'Essuie-glaces',
    emoji: '🚗',
    famille: 'gainage',
    phases: ['bloc'],
    stats: { gainage: 1, souplesse: 0.3 },
    difficulte: 4,
    mesure: 'reps',
    base: 12,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Sur le dos, jambes en l\'air, fais-les basculer de gauche à droite en contrôle.',
    niveauRequis: 7,
  },

  /* ------------------------------ Cardio ------------------------------ */
  {
    id: 'shadow_boxing',
    nom: 'Shadow boxing',
    emoji: '🥊',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 0.9, gainage: 0.2 },
    difficulte: 2,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Garde haute, enchaîne directs et crochets en bougeant les appuis.',
    astuce: 'Le meilleur cardio silencieux qui existe. Et ça défoule.',
    niveauRequis: 1,
  },
  {
    id: 'pas_chasses',
    nom: 'Pas chassés',
    emoji: '↔️',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 0.8 },
    difficulte: 2,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'normal',
    consigne: 'En position basse, déplace-toi latéralement sur 3 pas, puis reviens.',
    niveauRequis: 1,
  },
  {
    id: 'marche_pompe',
    nom: 'Chenille',
    emoji: '🐛',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 0.6, souplesse: 0.5, gainage: 0.4 },
    difficulte: 3,
    mesure: 'reps',
    base: 8,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Debout, penche-toi, marche avec les mains jusqu\'en planche, puis reviens.',
    niveauRequis: 2,
  },
  {
    id: 'montees_genoux',
    nom: 'Montées de genoux',
    emoji: '🏃',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 1 },
    difficulte: 2,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'bruyant',
    consigne: 'Cours sur place en montant les genoux le plus haut possible.',
    niveauRequis: 1,
  },
  {
    id: 'talons_fesses',
    nom: 'Talons-fesses',
    emoji: '🦵',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 0.9 },
    difficulte: 2,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'bruyant',
    consigne: 'Cours sur place en touchant les fesses avec les talons.',
    niveauRequis: 1,
  },
  {
    id: 'jumping_jacks',
    nom: 'Jumping jacks',
    emoji: '⭐',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 0.9 },
    difficulte: 2,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'bruyant',
    consigne: 'Saute en écartant jambes et bras, puis reviens.',
    niveauRequis: 1,
  },
  {
    id: 'corde_imaginaire',
    nom: 'Corde à sauter (sans corde)',
    emoji: '🪢',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 0.9 },
    difficulte: 2,
    mesure: 'temps',
    base: 45,
    materiel: [],
    bruit: 'bruyant',
    consigne: 'Petits sauts sur la pointe des pieds, poignets qui tournent.',
    niveauRequis: 1,
  },
  {
    id: 'skater',
    nom: 'Sauts du patineur',
    emoji: '⛸️',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 0.9, force: 0.3 },
    difficulte: 3,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'bruyant',
    consigne: 'Bondis latéralement d\'un pied sur l\'autre, en croisant la jambe arrière.',
    niveauRequis: 3,
  },
  {
    id: 'burpees',
    nom: 'Burpees',
    emoji: '😤',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 1, force: 0.5, gainage: 0.3 },
    difficulte: 4,
    mesure: 'reps',
    base: 8,
    materiel: [],
    bruit: 'bruyant',
    consigne: 'Squat, mains au sol, saut en planche, pompe, retour et saut vertical.',
    astuce: 'L\'exercice que tout le monde adore détester.',
    niveauRequis: 3,
  },
  {
    id: 'sprint_sur_place',
    nom: 'Sprint sur place',
    emoji: '⚡',
    famille: 'cardio',
    phases: ['bloc'],
    stats: { cardio: 1 },
    difficulte: 3,
    mesure: 'temps',
    base: 25,
    materiel: [],
    bruit: 'bruyant',
    consigne: 'Course sur place à fond, petits appuis très rapides.',
    niveauRequis: 2,
  },

  /* --------------------------- Retour au calme ------------------------ */
  {
    id: 'etirement_ischios',
    nom: 'Étirement ischios',
    emoji: '🧎',
    famille: 'mobilite',
    phases: ['retour_calme'],
    stats: { souplesse: 1 },
    difficulte: 1,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Assis jambes tendues, penche-toi vers les pieds, dos long.',
    astuce: 'Ne force pas : c\'est un étirement, pas un concours.',
    zones: ['jambes', 'hanches'],
    niveauRequis: 1,
  },
  {
    id: 'etirement_quadriceps',
    nom: 'Étirement quadriceps',
    emoji: '🦩',
    famille: 'mobilite',
    phases: ['retour_calme'],
    stats: { souplesse: 1 },
    difficulte: 1,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Debout, attrape ta cheville derrière toi, genoux serrés. Change à mi-temps.',
    zones: ['jambes'],
    niveauRequis: 1,
  },
  {
    id: 'etirement_pectoraux',
    nom: 'Ouverture de poitrine',
    emoji: '🕊️',
    famille: 'mobilite',
    phases: ['retour_calme'],
    stats: { souplesse: 1 },
    difficulte: 1,
    mesure: 'temps',
    base: 40,
    materiel: ['mur'],
    bruit: 'silencieux',
    consigne: 'Main à plat sur le mur, bras tendu, pivote le buste vers l\'extérieur.',
    zones: ['poitrine', 'epaules'],
    niveauRequis: 1,
  },
  {
    id: 'posture_enfant',
    nom: 'Posture de l\'enfant',
    emoji: '🧘',
    famille: 'mobilite',
    phases: ['retour_calme'],
    stats: { souplesse: 1 },
    difficulte: 1,
    mesure: 'temps',
    base: 45,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'À genoux, fesses sur les talons, bras tendus devant, front au sol. Respire.',
    zones: ['dos', 'hanches'],
    niveauRequis: 1,
  },
  {
    id: 'etirement_fessiers',
    nom: 'Étirement fessiers',
    emoji: '🍑',
    famille: 'mobilite',
    phases: ['retour_calme'],
    stats: { souplesse: 1 },
    difficulte: 1,
    mesure: 'temps',
    base: 40,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Sur le dos, cheville sur le genou opposé, ramène la cuisse vers toi.',
    zones: ['hanches', 'jambes'],
    niveauRequis: 1,
  },
  {
    id: 'cobra',
    nom: 'Cobra',
    emoji: '🐍',
    famille: 'mobilite',
    phases: ['retour_calme'],
    stats: { souplesse: 1 },
    difficulte: 1,
    mesure: 'temps',
    base: 35,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'À plat ventre, pousse sur les mains pour ouvrir la poitrine, bassin au sol.',
    zones: ['dos', 'poitrine'],
    niveauRequis: 1,
  },
  {
    id: 'etirement_nuque',
    nom: 'Détente de la nuque',
    emoji: '💆',
    famille: 'mobilite',
    phases: ['retour_calme'],
    stats: { souplesse: 0.8 },
    difficulte: 1,
    mesure: 'temps',
    base: 30,
    materiel: [],
    bruit: 'silencieux',
    consigne: 'Incline doucement la tête d\'un côté, main sur la tempe. Change de côté.',
    zones: ['nuque', 'epaules'],
    niveauRequis: 1,
  },
];

/** Index par identifiant, pour retrouver un exercice sans balayer la liste. */
export const EXERCICES_PAR_ID: Record<string, Exercice> = Object.fromEntries(
  CATALOGUE.map((e) => [e.id, e]),
);

export function exerciceParId(id: string): Exercice | undefined {
  return EXERCICES_PAR_ID[id];
}

export interface FiltreExercices {
  phase: Phase;
  niveau: number;
  materielDispo: Materiel[];
  silencieux: boolean;
  familles?: Famille[];
}

/**
 * Exercices jouables ici et maintenant : bon moment de la séance, niveau
 * atteint, matériel présent, et voisins épargnés si le mode silencieux est
 * actif.
 */
export function exercicesDisponibles(filtre: FiltreExercices): Exercice[] {
  return CATALOGUE.filter((e) => {
    if (!e.phases.includes(filtre.phase)) return false;
    if (e.niveauRequis > filtre.niveau) return false;
    if (filtre.silencieux && e.bruit === 'bruyant') return false;
    if (!e.materiel.every((m) => filtre.materielDispo.includes(m))) return false;
    if (filtre.familles && !filtre.familles.includes(e.famille)) return false;
    return true;
  });
}

/**
 * Zones sollicitées par une famille d'effort.
 *
 * Évite d'annoter les 45 exercices d'effort un par un : leur famille dit
 * déjà ce qu'ils mobilisent. Seuls les exercices de mobilité, qu'il faut
 * choisir finement, portent leurs zones explicitement.
 */
export const ZONES_PAR_FAMILLE: Record<Famille, ZoneCorps[]> = {
  pousse: ['poitrine', 'epaules'],
  tire: ['dos', 'epaules'],
  jambes: ['jambes', 'hanches'],
  gainage: ['tronc', 'dos'],
  cardio: ['jambes', 'hanches'],
  mobilite: [],
};

/** Zones qu'un exercice mobilise, qu'elles soient déclarées ou déduites. */
export function zonesDe(exercice: Exercice): ZoneCorps[] {
  return exercice.zones ?? ZONES_PAR_FAMILLE[exercice.famille];
}

/** Exercices qui viennent d'entrer dans le deck en passant au niveau `niveau`. */
export function exercicesDebloquesAuNiveau(niveau: number): Exercice[] {
  return CATALOGUE.filter((e) => e.niveauRequis === niveau);
}

/** Niveau maximum où un exercice se débloque : borne la promesse « ça continue ». */
export const NIVEAU_DERNIER_DEBLOCAGE = CATALOGUE.reduce(
  (max, e) => Math.max(max, e.niveauRequis),
  1,
);
